[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.17.0"

# API routes handled by Next.js plugin
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Dynamic pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 